[package]
name = "fixed_size_lru_map"
edition = "2018"
version = "0.5.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
publish = false

[dependencies]
parking_lot  = "0.11"

[dev-dependencies]
